# ('',)         ('',),
graph = {
    'Main Gate (MG)':[('Way AAA', 50), ('Way AAL', 49)],
    'Institute for Science and Technology Research (ISTR)':[('Way ABE',18)],
    'North Oval Runway (NOR)':[('Way AAM', 12), ('East Oval Runway (EOR)', 96), ('West Oval Runway (WOR)',91)],
    'East Oval Runway (EOR)':[('North Oval Runway (NOR)',96), ('South Oval Runway (SOR)',96)],
    'West Oval Runway (WOR)':[('Way AAH',67), ('North Oval Runway (NOR)', 91), ('South Oval Runway (SOR)',91), ('Grand Stand',14)],
    'South Oval Runway (SOR)':[('West Oval Runway (WOR)',91), ('East Oval Runway (EOR)',96), ('Way AAH',19)],
    'Food Nutrition Building (FN)':[('Way AAF',28), ('Way AAG',29)],
    'Interfaith Chapel':[('Way AAD',35), ('Way AAE',35), ('Way AAG',35)],
    'North Wing ground (NW1)':[('Way AAE',27), ('North Wing ground (NW2)',18), ('East Wing ground (EW4)',14)],
    'North Wing ground (NW2)':[('Way AAP',14) , ('North Wing ground (NW1)',18), ('West Wing ground (WW3)',14)],
    'East Wing ground (EW4)':[('North Wing ground (NW1)',14), ('Way AAE',32), ('Way AAF',58)],
    'East Wing ground (EW1)':[('Way AAF',29), ('Way AAI',10)],
    'East Wing ground (EW2)':[('Way AAI',10), ('Way AAJ',10)],
    'West Wing ground (WW1)':[('Way AAK', 29), ('Way AAN',14), ('U',12)],
    'West Wing ground (WW2)':[('Way AAN',12), ('Way AAO',11)],
    'West Wing ground (WW3)':[('North Wing ground (NW2)',14), ('North Wing ground (NW2)',14)],
    'PUP Swimming Pool(PSP)':[('Way ABA',32)],
    'Alumni Building (AL)':[('Way ABA',38)],
    'P.E Building (P.EB)':[('Way ABA',38)],
    'Grand Stand':[('West Oval Runway (WOR)',14)],
    'Ferry Terminal':[('Way AAJ',12)],
    'Linear Park':[('Way AAJ',59), ('Way AAK',18), ('Way AAN',25), ('Student Canteen',40)],
    'U':[('Way AAK',23), ('West Wing ground (WW1)',12), ('Way AAN',20)],
    'Sampaguita Building':[('Way AAO',21), ('Way AAN',11), ('Student Canteen',17)],
    'Student Canteen':[('Way AAN',30), ('Way AAO',25), ('linear park (LP)',40), ('Sampaguita Building', 17)],
    'Charlie Del Rosario':[('Way AAO',29), ('Way AAW',28), ('Way AAX',31)],
    'Laboratory High School':[('Way AAY',31), ('Way AAZ',15)],
    'Printing Press Building':[('Way AAZ',13)],
    'PUP Tennis Court':[('Way AAQ',18)],
    'PUP Open Court':[('Way AAQ',27), ('Way AAR',26)],
    'PUP Swimming Pool':[('Way ABA',32)],
    'Alumni Building':[('Way ABA',38)],
    'P.E Building':[('Way ABA',30)],
    'Lagoon entrance (LE1)':[('Way AAU',18), ('Way ABJ',50), ('Way ABI',28)],
    'Lagoon entrance (LE2)':[('Way AAW',19), ('Lagoon entrance (LE3)',33), ('Way ABK',30)],
    'Lagoon entrance (LE3)':[('Lagoon entrance (LE2)',33), ('Way ABJ',35), ('Way AAP',10)],
    'Ampitheather (AT)':[('Way ABI',43), ('Way ABJ',19)],
    'Ninoy Aquino Library and Learning Resource Center (NAL1)':[('Way AAY',53), ('Way AAX',42)],
    'Ninoy Aquino Library and Learning Resource Center (NAL2)':[('Way ABH',39)],
    'PUP Gymnasium (PG1)':[('Way ABD',10), ('Way ABE',16)],
    'Way AAA':[('Main Gate (MG)',50), ('Way AAL',9), ('Way AAB',70), ('Way AAQ',45), ('Way ABE',57)],
    'Way AAB':[('Way AAL',68), ('Way AAA',70), ('Way AAC',45)],
    'Way AAC':[('Way AAB',45), ('Way AAD',40)],
    'Way AAD':[('Way AAC',40), ('Way AAE',50), ('Interfaith Chapel',35), ('Way AAH',19)],
    'Way AAE':[('Way AAD',50), ('Way AAF',55), ('Interfaith Chapel',35), ('North Wing ground (NW1)',27), ('East Wing ground (EW4)',32)],
    'Way AAF':[('Way AAE',55), ('East Wing ground (EW4)',58), ('Food Nutrition Building (FN)',28), ('Way AAG',48), ('East Wing ground (EW1)',29)],
    'Way AAG':[('Way AAF',48), ('Food Nutrition Building (FN)',29), ('Interfaith Chapel',35), ('Way AAH',34), ('Way AAD',47)],
    'Way AAH':[('Way AAD',19), ('South Oval Runway (SOR)',42), ('West Oval Runway (WOR)',67), ('Way AAG',34)],
    'Way AAI':[('East Wing ground (EW2)',10), ('East Wing ground (EW1)',10)],
    'Way AAJ':[('East Wing ground (EW2)',40), ('Way AAK',40), ('Ferry Terminal (FT)',12), ('linear park (LP)',59)],
    'Way AAK':[('Way AAJ',40), ('West Wing ground (WW1)',29), ('linear park (LP)',18), ('U',23), ('Way AAN',42)],
    'Way AAL':[('Way AAA',9), ('Way AAB',68), ('Main Gate (MG)',49), ('Way AAM',38)],
    'Way AAM':[('Way AAL',38), ('North Oval Runway (NOR)',12)],
    'Way AAN':[('West Wing ground (WW1)',14), ('West Wing ground (WW2)',12), ('Way AAK',42), ('U',20), ('linear park (LP)',25), ('Sampaguita Building',11), ('Student Canteen',30), ('Way AAO',23)],
    'Way AAO':[('Way AAN',23), ('Student Canteen',25), ('West Wing ground (WW2)',11), ('Sampaguita Building',21), ('Charlie Del Rosario',29), ('Way AAV',37)],
    'Way AAP':[('Way AAV',22), ('West Wing ground (WW3)',14), ('North Wing ground (NW2)',14), ('Lagoon entrance (LE3)',10)],
    'Way AAQ':[('Way AAA',45), ('Way AAR',47), ('PUP Tennis Court',18), ('PUP Open Court',27)],
    'Way AAR':[('Way AAQ',47), ('PUP Open Court',26), ('Way AAS',28), ('Way AAT',18)],
    'Way AAS':[('Way AAU',27), ('Way ABA',18), ('Way AAR',28)],
    'Way AAT':[('Way AAR',18), ('Way AAU',20)],
    'Way AAU':[('Way AAS',27), ('Lagoon entrance (LE1)',18), ('Way AAT',20)],
    'Way AAV':[('Way AAW',33), ('Way AAP',22), ('Way AAO',37)],
    'Way AAW':[('Lagoon entrance (LE2)',19), ('Charlie Del Rosario',28), ('Way AAV',33), ('Way AAX',28)],
    'Way AAX':[('Charlie Del Rosario',31), ('Way AAW',28), ('Way AAY',82), ('Ninoy Aquino Library and Learning Resource Center (NAL1)',42)],
    'Way AAY':[('Way AAX',82), ('Way AAZ',45), ('Laboratory High School (LH1)',31), ('Ninoy Aquino Library and Learning Resource Center (NAL1)',53)],
    'Way AAZ':[('Way AAY',45), ('Laboratory High School (LH1)',15), ('Printing Press Building',13)],
    'Way ABA':[('Way AAS',18), ('Way ABB',25), ('Way ABF',36), ('PUP Swimming Pool(PSP)',32), ('Alumni Building (AL)',38), ('P.E Building (P.EB)',30)],
    'Way ABB':[('Way ABA',25), ('Way ABC',38)],
    'Way ABC':[('Way ABB',38), ('Way ABD',50)],
    'Way ABD':[('Way ABE',25), ('PUP Gymnasium (PG1)',10), ('Way ABC',50)],
    'Way ABE':[('PUP Gymnasium (PG1)',10), ('Way ABD',25), ('Way AAA',57), ('Institute for Science and Technology Research (ISTR)',18)],
    'Way ABF':[('Way ABA',36), ('Way ABG',20)],
    'Way ABG':[('Way ABH',27), ('Way ABF',20)],
    'Way ABH':[('Ninoy Aquino Library and Learning Resource Center (NAL2)',39), ('Way ABG',27)],
    'Way ABI':[('Lagoon entrance (LE1)',28), ('Way ABJ',24), ('Way ABK',35), ('Ampitheather (AT)',43)],
    'Way ABJ':[('Ampitheather (AT)',19), ('Way ABK',20), ('Lagoon entrance (LE3)',35), ('Lagoon entrance (LE1)',50)],
    'Way ABK':[('Way ABI',35), ('Way ABJ',20), ('Lagoon entrance (LE2)',30)],
}