ground = {
    'Main Gate (MG)':[('Way AAA (AAA)', 50), ('Way AAL (AAL)', 49)],
    'Institute for Science and Technology Research (ISTR)':[('Way ABE (ABE)',18)],
    'North Oval Runway (NOR)':[('Way AAM (AAM)', 12), ('East Oval Runway (EOR)', 96), ('West Oval Runway (WOR)',91)],
    'East Oval Runway (EOR)':[('North Oval Runway (NOR)',96), ('South Oval Runway (SOR)',96)],
    'West Oval Runway (WOR)':[('Way AAH (AAH)',67), ('North Oval Runway (NOR)', 91), ('South Oval Runway (SOR)',91), ('Grand Stand',14)],
    'South Oval Runway (SOR)':[('West Oval Runway (WOR)',91), ('East Oval Runway (EOR)',96), ('Way AAH (AAH)',19)],
    'Food Nutrition Building (FN)':[('Way AAF (AAF)',28), ('Way AAG (AAG)',29), ('Nutrition Veranda (NV)',3)],
    'Interfaith Chapel (IC)':[('Way AAD (AAD)',35), ('Way AAE (AAE)',35), ('Way AAG (AAG)',35)],
    'East Wing ground (EW4)':[('Way AAE (AAE)',32), ('Way AAF (AAF)',58),('Public Assitance Complaint Desk (PACD)',22),('Medical Clinic (MC)',7),('Dome East Hallway 1st (DEH1)',13)],
    'East Wing ground (EW2)':[('Way AAF (AAF)',10), ('Way AAJ (AAJ)',10), ('East Hallway 1 (EH1)',2)],
    'West Wing ground (WW2)':[('Way AAK (AAK)',42), ('U',20), ('Linear Park (LP2)',25), ('Sampaguita Building (SB)',11), ('Student Canteen (SC)',30), ('Way AAO (AAO)',23), ('West Hallway 1 (WH2)', 2)],
    'West Wing ground (WW3)': [('Dome West Hallway 1st (DWH1)',12), ('Public Assitance Complaint Desk (PACD)',6), ('West Wing Stairs 1A (WS1A)',3),('Way AAP (AAP)',14)],
    'PUP Swimming Pool(PSP)':[('Way ABA (ABA)',32)],
    'Alumni Building (AL)':[('Way ABA (ABA)',38)],
    'P.E Building (P.EB)':[('Way ABA (ABA)',38), ('CHK Veranda',1)],
    'Grand Stand':[('West Oval Runway (WOR)',14)],
    'Ferry Terminal':[('Way AAJ (AAJ)',12)],
    'Linear Park (LP1)':[('Way AAJ (AAJ)',59), ('Way AAK (AAK)',18), ('West Wing ground (WW2)',25), ('Student Canteen (SC)',40)],
    'Linear Park (LP3)':[('Student Canteen (SC)',40)],
    'U':[('Way AAK (AAK)',23), ('West Wing ground (WW2)',12), ('West Wing ground (WW2)',20)],
    'Sampaguita Building (SB)':[('Way AAO (AAO)',21), ('West Wing ground (WW2)',11), ('Student Canteen (SC)',17)],
    'Student Canteen (SC)':[('West Wing ground (WW2)',30), ('Way AAO (AAO)',25), ('Linear Park (LP3)',40), ('Sampaguita Building (SB)', 17)],
    'Linear Park (LP2)':[('Student Canteen (SC)',40),('Way AAJ (AAJ)',59),('Way AAK (AAK)',18),('West Wing ground (WW2)',25)],
    'Charlie Del Rosario (CDR)':[('Way AAO (AAO)',29), ('Way AAW (AAW)',28), ('Way AAX (AAX)',31), ('Charlie Entrance (CE)', 5)],
    'Laboratory High School':[('Way AAY (AAY)',31), ('Way AAZ (AAZ)',15)],
    'Printing Press Building':[('Way AAZ (AAZ)',13)],
    'PUP Tennis Court (PTC)':[('Way AAP (AAQ)',18)],
    'PUP Open Court (POC)':[('Way AAP (AAQ)',27), ('Way AAR (AAR)',26)],
    'PUP Swimming Pool':[('Way ABA (ABA)',32)],
    'Alumni Building':[('Way ABA (ABA)',38)],
    'Lagoon entrance (LE1)':[('Way AAU (AAU)',18), ('Lagoon 2 (L2)',50), ('Lagoon 1 (L1)',28)],
    'Lagoon entrance (LE2)':[('Way AAW (AAW)',19), ('Lagoon entrance (LE3)',33), ('Lagoon 3 (L3)',30)],
    'Lagoon entrance (LE3)':[('Lagoon entrance (LE2)',33), ('Lagoon 2 (L2)',35), ('Way AAP (AAP)',10)],
    'Ampitheather (AT)':[('Lagoon 1 (L1)',43), ('Lagoon 2 (L2)',19)],
    'Ninoy Aquino Library and Learning Resource Center (NAL1)':[('Way AAY (AAY)',53), ('Way AAX (AAX)',42), ('Main Lobby Library (mll)',7)],
    'Ninoy Aquino Library and Learning Resource Center (NAL2)':[('Way ABH (ABH)',39), ('hallway library left (hll)', 8)],
    'PUP Gymnasium (PG1)':[('Way ABD (ABD)',10), ('Way ABE (ABE)',16)],
    'Way AAA (AAA)':[('Main Gate (MG)',50), ('Way AAL (AAL)',9), ('Way AAB (AAB)',70), ('Way AAP (AAQ)',45), ('Way ABE (ABE)',57)],
    'Way AAB (AAB)':[('Way AAL (AAL)',68), ('Way AAA (AAA)',70), ('Way AAC (AAC)',45)],
    'Way AAC (AAC)':[('Way AAB (AAB)',45), ('Way AAD (AAD)',40)],
    'Way AAD (AAD)':[('Way AAC (AAC)',40), ('Way AAE (AAE)',50), ('Interfaith Chapel (IC)',35), ('Way AAH (AAH)',19)],
    'Way AAE (AAE)':[('Way AAD (AAD)',50), ('Way AAF (AAF)',55), ('Interfaith Chapel (IC)',35), ('East Wing ground (EW4)',32)],
    'Way AAF (AAF)':[('Way AAE (AAE)',55), ('East Wing ground (EW4)',58), ('Food Nutrition Building (FN)',28), ('Way AAG (AAG)',48), ('East Wing ground (EW2)',29)],
    'Way AAG (AAG)':[('Way AAF (AAF)',48), ('Food Nutrition Building (FN)',29), ('Interfaith Chapel (IC)',35), ('Way AAH (AAH)',34), ('Way AAD (AAD)',47)],
    'Way AAH (AAH)':[('Way AAD (AAD)',19), ('South Oval Runway (SOR)',42), ('West Oval Runway (WOR)',67), ('Way AAG (AAG)',34)],
    'Way AAJ (AAJ)':[('East Wing ground (EW2)',40), ('Way AAK (AAK)',40), ('Ferry Terminal (FT)',12), ('Linear Park (LP1)',59)],
    'Ferry Terminal (FT)':[('Way AAJ (AAJ)',12)],
    'Way AAK (AAK)':[('Way AAJ (AAJ)',40), ('West Wing ground (WW2)',29), ('Linear Park (LP1)',18), ('U',23), ('West Wing ground (WW2)',42)],
    'Way AAL (AAL)':[('Way AAA (AAA)',9), ('Way AAB (AAB)',68), ('Main Gate (MG)',49), ('Way AAM (AAM)',38)],
    'Way AAM (AAM)':[('Way AAL (AAL)',38), ('North Oval Runway (NOR)',12)],
    'Way AAO (AAO)':[('West Wing ground (WW2)',23), ('Student Canteen (SC)',25), ('West Wing ground (WW2)',11), ('Sampaguita Building (SB)',21), ('Charlie Del Rosario (CDR)',29), ('Way AAV (AAV)',37)],
    'Way AAP (AAP)':[('Way AAV (AAV)',22), ('West Wing ground (WW3)',14), ('Lagoon entrance (LE3)',10)],
    'Way AAP (AAQ)':[('Way AAA (AAA)',45), ('Way AAR (AAR)',47), ('PUP Tennis Court (PTC)',18), ('PUP Open Court (POC)',27)],
    'Way AAR (AAR)':[('Way AAP (AAQ)',47), ('PUP Open Court (POC)',26), ('Way AAS (AAS)',28), ('Way AAT (AAT)',18)],
    'Way AAS (AAS)':[('Way AAU (AAU)',27), ('Way ABA (ABA)',18), ('Way AAR (AAR)',28)],
    'Way AAT (AAT)':[('Way AAR (AAR)',18), ('Way AAU (AAU)',20)],
    'Way AAU (AAU)':[('Way AAS (AAS)',27), ('Lagoon entrance (LE1)',18), ('Way AAT (AAT)',20)],
    'Way AAV (AAV)':[('Way AAW (AAW)',33), ('Way AAP (AAP)',22), ('Way AAO (AAO)',37)],
    'Way AAW (AAW)':[('Lagoon entrance (LE2)',19), ('Charlie Del Rosario (CDR)',28), ('Way AAV (AAV)',33), ('Way AAX (AAX)',28)],
    'Way AAX (AAX)':[('Charlie Del Rosario (CDR)',31), ('Way AAW (AAW)',28), ('Way AAY (AAY)',82), ('Ninoy Aquino Library and Learning Resource Center (NAL1)',42)],
    'Way AAY (AAY)':[('Way AAX (AAX)',82), ('Way AAZ (AAZ)',45), ('Laboratory High School (LH1)',31), ('Ninoy Aquino Library and Learning Resource Center (NAL1)',53)],
    'Way AAZ (AAZ)':[('Way AAY (AAY)',45), ('Laboratory High School (LH1)',15), ('Printing Press Building',13)],
    'Laboratory High School (LH1)':[('Way AAZ (AAZ)',15),('Way AAY (AAY)',31)],
    'Way ABA (ABA)':[('Way AAS (AAS)',18), ('Way ABB (ABB)',25), ('Way ABF (ABF)',36), ('PUP Swimming Pool(PSP)',32), ('Alumni Building (AL)',38), ('P.E Building (P.EB)',30)],
    'Way ABB (ABB)':[('Way ABA (ABA)',25), ('Way ABC (ABC)',38)],
    'Way ABC (ABC)':[('Way ABB (ABB)',38), ('Way ABD (ABD)',50)],
    'Way ABD (ABD)':[('Way ABE (ABE)',25), ('PUP Gymnasium (PG1)',10), ('Way ABC (ABC)',50)],
    'Way ABE (ABE)':[('PUP Gymnasium (PG1)',10), ('Way ABD (ABD)',25), ('Way AAA (AAA)',57), ('Institute for Science and Technology Research (ISTR)',18)],
    'Way ABF (ABF)':[('Way ABA (ABA)',36), ('Way ABG (ABG)',20)],
    'Way ABG (ABG)':[('Way ABH (ABH)',27), ('Way ABF (ABF)',20)],
    'Way ABH (ABH)':[('Ninoy Aquino Library and Learning Resource Center (NAL2)',39), ('Way ABG (ABG)',27)],
    'Lagoon 1 (L1)':[('Lagoon entrance (LE1)',28), ('Lagoon 2 (L2)',24), ('Lagoon 3 (L3)',35), ('Ampitheather (AT)',43)],
    'Lagoon 2 (L2)':[('Ampitheather (AT)',19), ('Lagoon 1 (L1)',20), ('Lagoon entrance (LE3)',35), ('Lagoon entrance (LE1)',50)],
    'Lagoon 3 (L3)':[('Lagoon 3 (L3)',35), ('Lagoon 2 (L2)',20), ('Lagoon entrance (LE2)',30)],
}