
all_1st_UPDATED = {
    'East Wing ground (EW4)':[('Way AAE (AAE)',32), ('Way AAF (AAF)',58),('Public Assitance Complaint Desk (PACD)',22),('Medical Clinic (MC)',7),('Dome East Hallway 1st (DEH1)',13)],
    'East Wing ground (EW2)':[('Way AAF (AAF)',10), ('Way AAJ (AAJ)',10), ('East Hallway 1 (EH1)',2)],
    'West Wing ground (WW2)':[('Way AAK (AAK)',42), ('U',20), ('Linear Park (LP2)',25), ('Sampaguita Building (SB)',11), ('Student Canteen (SC)',30), ('Way AAO (AAO)',23), ('West Hallway 1 (WH2)', 2)],
    'Accounting Office Extension (AOE)': [('UR: Records Retrieval R3 (URRR3)',10), ('UR: Records Retrieval R5 (URRR5)',10)],
    'Admission and Registration Services Section (ARSS)': [('UR: Records Retrieval R6 (URRR6)',10), ('W115',5)],
    'CR East 1 (CRE1)': [('Department of Military Science and Tactics (DMST)',5), ('Inspection Management Office (IMO)',10)],
    'CCHO': [('Department of Military Science and Tactics (DMST)',5), ('Facility Management Office (FAMO)',5)],
    'Department of Military Science and Tactics (DMST)': [('CCHO',5), ('CR East 1 (CRE1)',5)],
    'Dental Clinic (DC)':[('Medical Health Services Director (MHSD)',15), ('PUP Multi-Purpose Cooperative (PUPMPC)',20)],
    'Dome East Hallway 1st (DEH1)': [('Dome Runway 1st (DR1)',12), ('Dome South Hallway 1st (DSH1)',12), ('Dome West Hallway 1st (DWH1)',24), ('East Wing Stairs 1A (ES1A)',12), ('Medical Clinic (MC)',12),('East Wing ground (EW4)',13)],
    'Dome South Hallway 1st (DSH1)': [('Dome East Hallway 1st (DEH1)',12), ('Dome Runway 1st (DR1)',12), ('UR: Records Retrieval R5 (URRR5)',20), ('South Hallway 1A (SH1A)',24), ('East Wing Stairs 1A (ES1A)',7), ('Dome West Hallway 1st (DWH1)',12),('Inspection Management Office (IMO)',22)],
    'Dome West Hallway 1st (DWH1)': [('Dome East Hallway 1st (DEH1)',24), ('Dome Runway 1st (DR1)',12), ('Dome South Hallway 1st (DSH1)',12), ('UR: Records Retrieval R5 (URRR5)',26), ('West Wing Stairs 1A (WS1A)',12), ('West Wing ground (WW3)',12)],
    'Dome Runway 1st (DR1)': [('Dome East Hallway 1st (DEH1)',12), ('Dome South Hallway 1st (DSH1)',12), ('Dome West Hallway 1st (DWH1)',12), ('Internal Audit Office (IAO)',2)],
    'East Hallway 1 (EH1)': [('East Wing Stairs 1B (ES1B)',1), ('Facility Management Office (FAMO)',16), ('PUP Multi-Purpose Cooperative (PUPMPC)',16), ('East Wing ground (EW2)',2)],
    'East Wing Stairs 1A (ES1A)': [('Dome East Hallway 1st (DEH1)',12), ('Dome South Hallway 1st (DSH1)',7), ('Inspection Management Office (IMO)',20),('East Wing Stairs 2A (ES2A)',6)],
    'East Wing Stairs 1B (ES1B)': [('East Hallway 1 (EH1)',1),('East Wing Stairs 2B (ES2B)',6)],
    'Fire Exit 1 (FR1)': [('S105 Office of the University Registrar 1 (OUR1)',9)],
    'Fire Exit 2 (FR2)': [('S103 Budget Services (BS)',9)],
    'Facility Management Office (FAMO)': [('CCHO',5), ('East Hallway 1 (EH1)',16)],
    'Internal Audit Office (IAO)': [('Dome Runway 1st (DR1)',2)],
    'Inspection Management Office (IMO)': [('CR East 1 (CRE1)',10), ('East Wing Stairs 1A (ES1A)',20),('Dome South Hallway 1st (DSH1)',22)],
    'Medical Clinic (MC)': [('Dome East Hallway 1st (DEH1)',12), ('Medical Health Services Director (MHSD)',15),('East Wing ground (EW4)',7)],
    'Medical Health Services Director (MHSD)': [('Dental Clinic (DC)',15), ('Medical Clinic (MC)',15)],
    'Public Assitance Complaint Desk (PACD)': [('West Wing ground (WW3)',5),('East Wing ground (EW4)',22)],
    'PUP Multi-Purpose Cooperative (PUPMPC)': [('Dental Clinic (DC)',20), ('East Hallway 1 (EH1)',16)],
    'Scholarahip Office (OSFA)': [('Scholarship and Financial Assistance Services (SFAS)',10), ('West Hallway 1 (WH2)',16)],
    'Scholarship and Financial Assistance Services (SFAS)': [('Scholarahip Office (OSFA)',10), ('W115',10)],
    'Office of the University Registrar: Records Retrieval Section (OURRRS)': [('West Hallway 1 (WH2)',16), ('UR: Records Retrieval R3 (URRR3)',10)],
    'South Hallway 1A (SH1A)': [('S109 Accounting Office (AO)',10), ('Dome South Hallway 1st (DSH1)',24), ('South Hallway 1B (SH1B)',22), ('South Hallway 1D (SH1D)',22),('South Wing Stairs 1B (SS1B)',6)],
    'South Hallway 1B (SH1B)': [('South Wing Stairs 1A (SS1A)',4), ('S107 Accounting Division Student Services Section (ADSSS)',4), ('S108 (S108)',4), ('South Hallway 1A (SH1A)',22), ('South Hallway 1C (SH1C)',4)],
    'South Hallway 1C (SH1C)': [('S106 Payroll Section (PS)',4), ('South Hallway 1B (SH1B)',4)],
    'South Hallway 1D (SH1D)': [('S101 Fund Management Office (FMO)',4), ('South Hallway 1A (SH1A)',22), ('South Hallway 1E (SH1E)',4), ('South Wing Stairs 1C (SS1C)',4)],
    'South Hallway 1E (SH1E)': [('S103 Budget Services (BS)',4), ('S102 (S102)',4),('South Hallway 1D (SH1D)',4)],
    'S101 Fund Management Office (FMO)': [('South Hallway 1D (SH1D)',4)],
    'S102 (S102)': [('South Hallway 1E (SH1E)',4)],
    'S103 Budget Services (BS)': [('Fire Exit 2 (FR2)',9), ('S104 Office of the University Registrar 2 (OUR2)',20), ('South Hallway 1E (SH1E)',4)],
    'S104 Office of the University Registrar 2 (OUR2)': [('S103 Budget Services (BS)',20), ('S105 Office of the University Registrar 1 (OUR1)',20), ('South Wing Stairs 1B (SS1B)',10)],
    'S105 Office of the University Registrar 1 (OUR1)': [('Fire Exit 1 (FR1)',9), ('S104 Office of the University Registrar 2 (OUR2)',20), ('S106 Payroll Section (PS)',4)],
    'S106 Payroll Section (PS)': [('S105 Office of the University Registrar 1 (OUR1)',4), ('South Hallway 1C (SH1C)',4)],
    'S107 Accounting Division Student Services Section (ADSSS)': [('South Hallway 1B (SH1B)',4)],
    'S108 (S108)': [('S109 Accounting Office (AO)',10), ('South Hallway 1B (SH1B)',4)],
    'S109 Accounting Office (AO)': [('S108 (S108)',10), ('South Hallway 1A (SH1A)',10)],
    'South Wing Stairs 1A (SS1A)': [('South Hallway 1B (SH1B)',4),('South Wing Stairs 2A (SS2A)',6)],
    'South Wing Stairs 1B (SS1B)': [('South Hallway 1A (SH1A)',6),('S104 Office of the University Registrar 2 (OUR2)',10),('South Wing Stairs 2B (SS2B)',6)],
    'South Wing Stairs 1C (SS1C)': [('South Hallway 1D (SH1D)',4),('South Wing Stairs 2C (SS2C)',6)],
    'West Hallway 1 (WH2)': [('Scholarahip Office (OSFA)',16), ('Office of the University Registrar: Records Retrieval Section (OURRRS)',16), ('West Wing Stairs 1B (WS1B)',2),('West Wing ground (WW2)',2)],
    'West Wing Stairs 1B (WS1B)': [('West Hallway 1 (WH2)',2),('West Wing Stairs 2B (WS2B)',6)],
    'West Wing Stairs 1A (WS1A)': [('Dome West Hallway 1st (DWH1)',12), ('UR: Records Retrieval R6 (URRR6)',5), ('West Wing ground (WW3)',4),('West Wing Stairs 2A (WS2A)',6)],
    'West Wing ground (WW3)': [('Dome West Hallway 1st (DWH1)',12), ('Public Assitance Complaint Desk (PACD)',5), ('West Wing Stairs 1A (WS1A)',4)],
    'W115': [('Admission and Registration Services Section (ARSS)',5), ('Scholarship and Financial Assistance Services (SFAS)',10)],
    'UR: Records Retrieval R3 (URRR3)': [('Accounting Office Extension (AOE)',10), ('Office of the University Registrar: Records Retrieval Section (OURRRS)',10)],
    'UR: Records Retrieval R5 (URRR5)': [('Accounting Office Extension (AOE)',10), ('Dome South Hallway 1st (DSH1)',20), ('Dome West Hallway 1st (DWH1)',26)],
    'UR: Records Retrieval R6 (URRR6)': [('Admission and Registration Services Section (ARSS)',10), ('West Wing Stairs 1A (WS1A)',5)]
}
